// src/components/pageview-counter.tsx
"use client";

import { useEffect, useState } from "react";

export default function PageviewCounter({ slug }: { slug: string }) {
  const [count, setCount] = useState<number | null>(null);

  useEffect(() => {
    let mounted = true;

    async function fetchCount() {
      try {
        const res = await fetch(
          `/api/pageview?slug=${encodeURIComponent(slug)}`
        );
        if (!res.ok) {
          return;
        }
        const data = await res.json();
        if (mounted && typeof data.count === "number") {
          setCount(data.count);
        }
      } catch {
        // ignore errors
      }
    }

    fetchCount();

    return () => {
      mounted = false;
    };
  }, [slug]);

  if (count === null) {
    return (
      <p className="inline-flex items-center gap-1 text-muted-foreground text-sm">
        Loading…
      </p>
    );
  }

  return (
    <p className="inline-flex items-center gap-1 text-muted-foreground text-sm">
      {count} view{count > 1 ? "s" : ""}
    </p>
  );
}

// src/components/page-view-counter.svelte
<script lang="ts">
  import { api } from "@zap-studio/fetch";
  import { z } from "astro/zod";
  import { onMount } from "svelte";

  type Props = {
    slug: string;
  };

  let { slug }: Props = $props();

  const PageCountSchema = z.object({
    count: z.number(),
  });

  let pageViewCount: number | null = $state(null);
  let isLoaded = $state(false);

  onMount(async () => {
    try {
      const result = await api.get(
        `/api/pageview?slug=${encodeURIComponent(slug)}`,
        PageCountSchema
      );
      pageViewCount = result.count;
    } finally {
      isLoaded = true;
    }
  });
</script>

{#if isLoaded && pageViewCount !== null}
  <p class="inline-flex items-center gap-1 text-muted-foreground text-sm">
    {pageViewCount}view{pageViewCount !== 1 ? "s" : ""}
  </p>
{/if}
